services:
  nginx:
    image: nginx_server
    user: root
    ports:
      - "80:80"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    user: root
    ports:
      - "3000:3000"
    volumes:
      - /grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    user: root
    ports:
      - "9090:9090"
    volumes:
      - /prometheus:/prometheus
      - /tmp/code/prometheus-conf:/etc/prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
